packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@cloudflare/workers-types': ^4.20250723.0
  '@orpc/client': 1.7.4
  '@orpc/openapi': 1.7.4
  '@orpc/server': 1.7.4
  '@orpc/tanstack-query': 1.7.4
  '@orpc/zod': 1.7.4
  '@tanstack/react-form': 1.14.2
  '@tanstack/react-query': 5.83.0
  '@types/node': 24.0.14
  '@vitejs/plugin-react': ^4.7.0
  '@vitejs/plugin-react-oxc': ^0.3.0
  better-auth: ^1.3.2
  hono: ^4.8.5
  superjson: ^2.2.2
  tailwindcss: ^4.1.3
  tsdown: 0.13.0
  typescript: ^5.8.3
  vite: npm:rolldown-vite@^7.0.11
  wrangler: ^4.26.0
  zod: ^3.25.75

catalogs:
  react19:
    '@types/react': ^19.1.6
    '@types/react-dom': ^19.1.5
    react: ^19.0.0
    react-dom: ^19.0.0
  tailwind3:
    tailwindcss: ^3.4.17
  tailwind4:
    tailwindcss: ^4.1.11

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js-pure
  - esbuild
  - sharp
  - workerd
